# Generated by Django 3.0.8 on 2020-07-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45)),
                ('slot', models.IntegerField(default=0)),
                ('url', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45)),
                ('tamanho', models.IntegerField(default=0)),
                ('ordem', models.CharField(default='', max_length=45)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Tipo')),
            ],
        ),
    ]
