# Generated by Django 3.0.8 on 2020-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20200708_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
