# Generated by Django 3.0.8 on 2020-07-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20200708_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
